[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[profile.deploy]
gas_price = 'auto'

remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
